[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:roloenusa/nvim.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"


