# ~/.config/starship.toml

[username]
style_user = "green bold"
style_root = "red bold"
format = "[➜ $user]($style) "
disabled = false
show_always = true

[git_status]
stashed = ''

[nodejs]
style = 'green'
version_format = 'v${major}'
